version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake spec"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
